# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-01 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant_app', '0002_auto_20190201_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='res_photos/default.png', upload_to='res_photos/'),
        ),
    ]
